import '../models/inspection_step.dart';

/// 1 arrival check + 12 capture steps covering all 73 schema checkpoints.
const List<InspectionStep> kInspectionSteps = [
  InspectionStep(
    id: 'arrival',
    section: StepSection.arrival,
    type: StepType.arrival,
    titleKey: 'stepArrivalTitle',
    instructionKey: 'stepArrivalInstruction',
  ),
  InspectionStep(
    id: 'rc_document',
    section: StepSection.documents,
    type: StepType.photo,
    titleKey: 'stepRcTitle',
    instructionKey: 'stepRcInstruction',
    referenceImagePath: 'assets/references/rc_document.jpg',
  ),
  InspectionStep(
    id: 'instrument_cluster',
    section: StepSection.interior,
    type: StepType.photo,
    titleKey: 'stepClusterTitle',
    instructionKey: 'stepClusterInstruction',
    referenceImagePath: 'assets/references/instrument_cluster.jpg',
  ),
  InspectionStep(
    id: 'engine_bay',
    section: StepSection.mechanical,
    type: StepType.photo,
    titleKey: 'stepEngineBayTitle',
    instructionKey: 'stepEngineBayInstruction',
    referenceImagePath: 'assets/references/engine_bay.jpg',
  ),
  InspectionStep(
    id: 'front_full',
    section: StepSection.exterior,
    type: StepType.photo,
    titleKey: 'stepFrontTitle',
    instructionKey: 'stepFrontInstruction',
    referenceImagePath: 'assets/references/front_full.jpg',
  ),
  InspectionStep(
    id: 'lhs_full',
    section: StepSection.exterior,
    type: StepType.photo,
    titleKey: 'stepLeftTitle',
    instructionKey: 'stepLeftInstruction',
    referenceImagePath: 'assets/references/lhs_full.jpg',
  ),
  InspectionStep(
    id: 'rhs_full',
    section: StepSection.exterior,
    type: StepType.photo,
    titleKey: 'stepRightTitle',
    instructionKey: 'stepRightInstruction',
    referenceImagePath: 'assets/references/rhs_full.jpg',
  ),
  InspectionStep(
    id: 'rear_full',
    section: StepSection.exterior,
    type: StepType.photo,
    titleKey: 'stepRearTitle',
    instructionKey: 'stepRearInstruction',
    referenceImagePath: 'assets/references/rear_full.jpg',
  ),
  InspectionStep(
    id: 'roof',
    section: StepSection.exterior,
    type: StepType.photo,
    titleKey: 'stepRoofTitle',
    instructionKey: 'stepRoofInstruction',
    referenceImagePath: 'assets/references/roof.jpg',
  ),
  InspectionStep(
    id: 'interior',
    section: StepSection.interior,
    type: StepType.photo,
    titleKey: 'stepInteriorTitle',
    instructionKey: 'stepInteriorInstruction',
    referenceImagePath: 'assets/references/interior.jpg',
  ),
  InspectionStep(
    id: 'tyres',
    section: StepSection.exterior,
    type: StepType.multiPhoto,
    titleKey: 'stepTyresTitle',
    instructionKey: 'stepTyresInstruction',
    referenceImagePath: 'assets/references/tyre.jpg',
    photoCount: 4,
  ),
  InspectionStep(
    id: 'engine_sound',
    section: StepSection.mechanical,
    type: StepType.audio,
    titleKey: 'stepEngineSoundTitle',
    instructionKey: 'stepEngineSoundInstruction',
    referenceImagePath: 'assets/references/engine_sound.jpg',
    audioSeconds: 15,
  ),
  InspectionStep(
    id: 'test_drive',
    section: StepSection.testDrive,
    type: StepType.voiceQA,
    titleKey: 'stepTestDriveTitle',
    instructionKey: 'stepTestDriveInstruction',
    referenceImagePath: 'assets/references/test_drive.jpg',
  ),
];
